name: notes_app

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_test:
    sdk: flutter
    version: ^0.0.0
  freezed_annotation: ^1.1.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.8
  google_sign_in: ^5.2.3
  get_it: ^7.2.0
  injectable: ^1.5.3
  another_flushbar: ^1.10.28
  uuid: ^3.0.4
  auto_route: ^3.2.2
  flutter_hooks: ^0.18.2+1
  kt_dart: ^0.10.0
  json_annotation: ^4.4.0
  rxdart: ^0.27.3
  provider: ^6.0.2
  flutter_slidable: ^1.2.0
  implicitly_animated_reorderable_list: ^0.4.2
  hydrated_bloc: ^8.0.0
  path_provider: ^2.0.9
  connectivity_plus: ^2.2.1


dev_dependencies:
  build_runner: null
  freezed: ^1.1.1
  very_good_analysis: ^2.4.0
  injectable_generator: ^1.5.3
  auto_route_generator: ^3.2.1
  json_serializable: ^6.1.4

flutter:

  uses-material-design: true
