name: notes_app

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_test:
    sdk: flutter
    version: ^0.0.0
  freezed_annotation: ^1.1.0
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  google_sign_in: ^5.2.3
  get_it: ^7.2.0
  injectable: ^1.5.3
  



dev_dependencies:
  build_runner: null
  freezed: ^1.1.1
  very_good_analysis: ^2.4.0
  injectable_generator: ^1.5.3

flutter:

  uses-material-design: true
